#!/bin/bash

export LD_LIBRARY_PATH=''
# asetup 17.3.5,AtlasProduction
source $AtlasSetup/scripts/asetup.sh 17.3.5,AtlasProduction
export JOBOPTSEARCHPATH=/cvmfs/atlas.cern.ch/repo/sw/Generators/MC12JobOptions/latest/common:$JOBOPTSEARCHPATH
